#Repo at the point it "worked" https://github.com/apache/grails-core/blob/498f0b4500b4a8e97cc4a95744d466fb089aac76/

grailsVersion=7.0.0-20240926.044355-61
grailsBomVersion=7.0.0-20240926.044355-61
grailsGradlePluginVersion=7.0.0-20240924.041621-24
gspVersion=7.0.0-20240925.183809-16
hibernate5Version=9.0.0-20240924.215449-12
datastoreGormHhibernate5Version=9.0.0-20240924.215449-13
scaffoldingVersion=6.0.0-20240923.232107-7
springSecurityCoreVersion=7.0.0-20241009.065849-9
groovyVersion=4.0.22
spring-boot.version=3.3.4
springBootVersion=3.3.4
profileVersion=7.0.1
gormVersion=9.0.0-20240924.041938-11
convertersVersion=6.0.0-20240924.041442-7
asyncVersion=7.0.0-20240924.041556-5
fieldsVersion=6.0.0-20240924.183515-2

geb.version=4.0.0
mongodb.version=5.1.4
mongodb.bson.version=5.1.4
scaffoldingCore.version=2.1.0
spring.version=6.1.13
directoryWatcher.version=0.18.0
spock.version=2.3-groovy-4.0
tomcatJDBCVersion=10.1.30



version=0.1
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx1024M
